print('Input coordinate A')
A = float(input())
print('Input coordinate B')
B = float(input())
print('Input coordinate C')
C = float(input())
AC = abs(A-C)
BC = abs(B-C)
print('AC+BC length is', AC+BC)
